# Generated by Django 3.2.13 on 2022-06-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                ("bio", models.TextField()),
                ("email", models.EmailField(max_length=254, null=True)),
                ("github", models.URLField(null=True)),
                ("linkedin", models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hobby",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hobby", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("img", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tag", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("img", models.URLField()),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[("cert", "Certification"), ("edu", "Education"), ("proj", "Project")], max_length=4
                    ),
                ),
                ("tag", models.ManyToManyField(blank=True, to="resume.Tag")),
            ],
        ),
    ]
