# Generated by Django 3.2.13 on 2022-06-26 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fullname", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("bio", models.TextField()),
                ("github", models.URLField(null=True)),
                ("linkedin", models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tag", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("role", "Role"),
                            ("cert", "Certification"),
                            ("edu", "Education"),
                            ("proj", "Project"),
                        ],
                        max_length=4,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(null=True)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="resume.profile")),
                ("tag", models.ManyToManyField(blank=True, to="resume.Tag")),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Hobby",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("img", models.CharField(max_length=128)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="resume.profile")),
            ],
        ),
    ]
