# Generated by Django 3.2.13 on 2022-09-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutme",
            options={"verbose_name": "About Me", "verbose_name_plural": "About Me"},
        ),
        migrations.AlterModelOptions(
            name="hobby",
            options={"ordering": ["hobby"], "verbose_name": "Hobby", "verbose_name_plural": "Hobbies"},
        ),
        migrations.AlterModelOptions(
            name="milestone",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="workhistory",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Work History",
                "verbose_name_plural": "Work History",
            },
        ),
        migrations.AddField(
            model_name="aboutme",
            name="resume",
            field=models.URLField(null=True),
        ),
    ]
